import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Header from "@/components/shared/Header";
import Footer from '@/components/shared/Footer';

const roboto = Roboto(
  {
    subsets: ['latin'],
    style: ['normal'],
    weight: ['400','500'],
    display: 'swap'
  }
)

export const metadata: Metadata = {
  title: {
    default: 'Apple Market',
    template: '%s | Apple Market'
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const developer = {
    label: 'Developed by:',
    name: 'Sofia Ferreira',
    link: 'https://github.com/SofiaFerreira77/beer-collection-case'
  }

  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer developer={developer} />
      </body>
    </html>
  )
}
